Feature/pg migrate
Start9Labs/mastodon-wrapper pull request #12
Opened 2022-01-18 01:23 UTC by chrisguida

2022-01-19 18:54 UTC, dr-bonez requested changes

2022-01-19 18:54 UTC, dr-bonez commented on docker_entrypoint.sh
> +    echo 'postgres not ready, retrying in 1 second...'
```suggestion
    >&2 echo 'postgres not ready, retrying in 1 second...'
```

2022-01-19 18:54 UTC, dr-bonez commented on pg-migrate/docker_entrypoint.sh
> +  exit 1
on exit 1, the install should fail - so MigrationRes shouldn't be necessary

2022-01-19 18:58 UTC, dr-bonez commented on manifest.yaml
> +      args: ["-c", 'json=''{"configured": true }'' && echo "$json"']
will this work?? I don't think we can safely downgrade from this version ever

2022-01-19 19:10 UTC, chrisguida commented on manifest.yaml
> +      args: ["-c", 'json=''{"configured": true }'' && echo "$json"']
`embassy-sdk` wouldn't let me build without `to`

2022-01-19 19:30 UTC, chrisguida commented on pg-migrate/docker_entrypoint.sh
> +  exit 1
removed

2022-01-19 20:09 UTC, dr-bonez commented on manifest.yaml
> +      args: ["-c", 'json=''{"configured": true }'' && echo "$json"']
use an empty array

2022-01-19 20:59 UTC, dr-bonez commented on pg-migrate/docker_entrypoint.sh
> +  exit 1
still might want an actual error message here?

2022-01-20 18:25 UTC, chrisguida commented on pg-migrate/docker_entrypoint.sh
> +  exit 1
added

2022-01-20 18:25 UTC, chrisguida commented on manifest.yaml
> +      args: ["-c", 'json=''{"configured": true }'' && echo "$json"']
done

2022-01-21 00:54 UTC, dr-bonez approved these changes

2022-01-21 17:05 UTC, merged